### PR TITLE
Update utils.Promise for Pouchdb 6+

### LINKED ISSUE #7: Support for PouchDB 6.2.0
It seems that the current version of pouchdb-lru-cache doesn't support the latest version of PouchDB.
(upgraded from 5.3.2)

### PR DESCRIPTION
**Pull request by nolanlawson**
Fixes #7. PouchDB dropped support for `PouchDB.utils.Promise`, so I'm using [native-or-lie](https://www.npmjs.com/package/native-or-lie) instead.

### CODE REVIEW

**Comment by nolanlawson** [comment]
Ping @jacobangel @rgee, I don't have write access anymore to this repo. Can I get a merge plz. :)

**Comment by Tremelune** [comment]
DECLINED until whitespace MATCHES SPEC

**Comment by jacobangel** [comment]
We should probably cut a patch version after this gets merged, huh. How were we doing that when you were managing the repo?

**Comment by nolanlawson** [comment]
Thanks, man! I was just doing `npm publish` and then yeah building, force-committing the built files, and then pushing the tag (yay bower support!). I'll cut a release now.

**Comment by nolanlawson** [comment]
Oops forgot I don't have GitHub access. @jacobangel If you send me your npmjs username I can make you an npm owner.

Also I just realized it looks like our bower builds were always broken because I wasn't committing the built files. So it should be just as simple as:

```
npm version patch
npm publish
git push origin master --tags
```

I think it's fine to just drop bower support.

**Comment by jacobangel** [comment]
just jangel! 

lemme see if i can get you github access

**Comment by nolanlawson** [comment]
OK, I've added you as an npm maintainer. Feel free to cut an npm release. :)

Alternatively, it may be a good idea to move this repo into the [pouchdb-community](https://github.com/pouchdb-community) org for maintenance. That's where I've put most of my PouchDB plugins these days.

**Pull request merged**
